{{- if and .Values.serviceMonitor.endpoints (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
{{- with .Values.serviceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vector.fullname" $ }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- with .additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "vector.labels" $ | nindent 4 }}
spec:
  {{- with .jobLabel }}
  jobLabel: "{{ . }}"
  {{- end }}
  selector:
    matchLabels:
      {{- include "vector.selectorLabels" $ | nindent 6 }}
  {{- with .namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  endpoints:
    {{- toYaml .endpoints | nindent 4 }}
{{- end }}
{{- end }}
